{% set name = "perfplot" %}
{% set version = "0.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/perfplot-{{ version }}.tar.gz
  sha256: d76daa72334564b5c8825663f24d15db55ea33e938b34595a146e5e44ed87e41

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
    - matplotlib-base
    - matplotx
    - numpy >=1.20
    - python {{ python_min }}
    - rich
    - typing_extensions
  run:
    - matplotlib-base
    - matplotx
    - numpy >=1.20
    - python >={{ python_min }}
    - rich
    - typing_extensions

test:
  imports:
    - perfplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nschloe/perfplot
  summary: Performance plots for Python code snippets
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
